--
-- ====================
-- DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
--
-- Copyright 2008-2009 Sun Microsystems, Inc. All rights reserved.
-- Copyright 2011-2013 Tirasa. All rights reserved.
--
-- The contents of this file are subject to the terms of the Common Development
-- and Distribution License("CDDL") (the "License"). You may not use this file
-- except in compliance with the License.
--
-- You can obtain a copy of the License at https://oss.oracle.com/licenses/CDDL
-- See the License for the specific language governing permissions and limitations
-- under the License.
--
-- When distributing the Covered Code, include this CDDL Header Notice in each file
-- and include the License file at https://oss.oracle.com/licenses/CDDL.
-- If applicable, add the following below this CDDL Header, with the fields
-- enclosed by brackets [] replaced by your own identifying information:
-- "Portions Copyrighted [year] [name of copyright owner]"
-- ====================
--

CREATE TABLE PUBLIC.user(
capsId INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
userId VARCHAR(30) NOT NULL,
password VARCHAR(255) NOT NULL,
type VARCHAR(17) NOT NULL,
residence VARCHAR(60),
telephone VARCHAR(20),
fax VARCHAR(20),
preference VARCHAR(120),
name VARCHAR(30),
surname VARCHAR(35),
fullname VARCHAR(35) NOT NULL,
birthdate VARCHAR(30),
gender VARCHAR(1),
taxNumber VARCHAR(30),
state VARCHAR(15),
studyTitle VARCHAR(30),
studyArea VARCHAR(30),
job VARCHAR(30),
companyType VARCHAR(30),
companyName VARCHAR(30),
vatNumber VARCHAR(30),
mandatoryDisclaimer BOOLEAN,
promoRCSDisclaimer BOOLEAN,
promoThirdPartyDisclaimer BOOLEAN,
UNIQUE(userId))
