--
-- Copyright (C) ${project.inceptionYear} ConnId (connid-dev@googlegroups.com)
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--         http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE PUBLIC.user(
capsId INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
userId VARCHAR(30) NOT NULL,
password VARCHAR(255) NOT NULL,
type VARCHAR(17) NOT NULL,
residence VARCHAR(60),
telephone VARCHAR(20),
fax VARCHAR(20),
preference VARCHAR(120),
name VARCHAR(30),
surname VARCHAR(35),
fullname VARCHAR(35) NOT NULL,
birthdate VARCHAR(30),
gender VARCHAR(1),
taxNumber VARCHAR(30),
state VARCHAR(15),
studyTitle VARCHAR(30),
studyArea VARCHAR(30),
job VARCHAR(30),
companyType VARCHAR(30),
companyName VARCHAR(30),
vatNumber VARCHAR(30),
mandatoryDisclaimer BOOLEAN,
promoRCSDisclaimer BOOLEAN,
promoThirdPartyDisclaimer BOOLEAN,
UNIQUE(userId))

CREATE TABLE PUBLIC.role(
roleId INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
roleName VARCHAR(120),
UNIQUE(roleName))
